force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>My Opportunity</label>
    <nameField>
        <displayFormat>ON-{0000}</displayFormat>
        <label>Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Product Description</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Additional_To__c.field-meta.xml
<CustomField>
    <fullName>Additional_To__c</fullName>
    <label>Additional To</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Additional_To_Name__c.field-meta.xml
<CustomField>
    <fullName>Additional_To_Name__c</fullName>
    <label>Additional To Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <label>Bill To</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Bill_To_Name__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Name__c</fullName>
    <label>Bill To Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/ContractId__c.field-meta.xml
<CustomField>
    <fullName>ContractId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>ExpirationDate__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/GrandTotal__c.field-meta.xml
<CustomField>
    <fullName>GrandTotal__c</fullName>
    <formula>(TotalPrice__c-( TotalPrice__c * Discount__c ))+ ShippingHandling__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/IsSyncing__c.field-meta.xml
<CustomField>
    <fullName>IsSyncing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Syncing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/LineItemCount__c.field-meta.xml
<CustomField>
    <fullName>LineItemCount__c</fullName>
    <label>Line Items</label>
    <summaryForeignKey>QuoteLineItem__c.QuoteId__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/QuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteNumber__c</fullName>
    <displayFormat>{00000000}</displayFormat>
    <label>Quote Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/QuoteToAddress__c.field-meta.xml
<CustomField>
    <fullName>QuoteToAddress__c</fullName>
    <label>Quote To</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/QuoteToName__c.field-meta.xml
<CustomField>
    <fullName>QuoteToName__c</fullName>
    <label>Quote To Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/ShippingAddress__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddress__c</fullName>
    <label>Ship To</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/ShippingHandling__c.field-meta.xml
<CustomField>
    <fullName>ShippingHandling__c</fullName>
    <label>Shipping and Handling</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/ShippingName__c.field-meta.xml
<CustomField>
    <fullName>ShippingName__c</fullName>
    <label>Ship To Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <label>Subtotal</label>
    <summarizedField>QuoteLineItem__c.Subtotal__c</summarizedField>
    <summaryForeignKey>QuoteLineItem__c.QuoteId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>Total Price</label>
    <summarizedField>QuoteLineItem__c.TotalPrice__c</summarizedField>
    <summaryForeignKey>QuoteLineItem__c.QuoteId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem__c/QuoteLineItem__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item</label>
    <nameField>
        <label>Quote Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteLineItem__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Line Item Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote Name</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/customQuoteController.cls
public class customQuoteController {
    public String quoteId { get; set; }
    public Quote__c Quote{get;set;}
    public List<Product__c> prodlist{get;set;}
    public list<QuoteLineItem__c> quoteLineItem{get;set;}
    public string recordId;
    public  User us{get;set;}
    
    
    
    public customQuoteController(){
      
        quoteId = ApexPages.currentPage().getParameters().get('id');
        System.debug('quoteId => '+quoteId);
        String currentUserId = UserInfo.getUserId();
        System.debug('Current User ID: ' + currentUserId);
        
        system.debug(quoteId);
       Quote= [SELECT LastModifiedById, Id, Name, CreatedDate, LastModifiedDate,
                CreatedById, Additional_To__Street__s, Account_Name__c, Additional_To__City__s,
                Additional_To__StateCode__s, Additional_To__PostalCode__s, Additional_To__CountryCode__s,
                Additional_To__Latitude__s, Additional_To__Longitude__s, Additional_To__GeocodeAccuracy__s, Additional_To__c,
                Additional_To_Name__c, Bill_To__Street__s, Bill_To__City__s, Bill_To__PostalCode__s, Bill_To__StateCode__s,
                Bill_To__CountryCode__s, Bill_To__Latitude__s, Bill_To__Longitude__s, Bill_To__GeocodeAccuracy__s, Bill_To__c, 
                Bill_To_Name__c, ContactId__c, ContractId__c, Description__c, Discount__c, Email__c, ExpirationDate__c, Fax__c,
                GrandTotal__c, Opportunity__c, QuoteNumber__c, Phone__c, QuoteToAddress__Street__s, QuoteToAddress__City__s, 
                QuoteToAddress__PostalCode__s, QuoteToAddress__StateCode__s, QuoteToAddress__CountryCode__s, QuoteToAddress__Latitude__s,
                QuoteToAddress__Longitude__s, QuoteToAddress__GeocodeAccuracy__s, QuoteToAddress__c, QuoteToName__c, ShippingAddress__Street__s,
                ShippingAddress__City__s, ShippingAddress__PostalCode__s, ShippingAddress__StateCode__s, ShippingAddress__CountryCode__s,
                ShippingAddress__Latitude__s, ShippingAddress__Longitude__s, ShippingAddress__GeocodeAccuracy__s, ShippingAddress__c, ShippingName__c,
                ShippingHandling__c, Status__c, IsSyncing__c, Tax__c, LineItemCount__c,Account_Name__r.Name,  
                TotalPrice__c, Subtotal__c, Primary__c FROM Quote__c where Id =:quoteId];
        system.debug('Quote=>'+Quote);
      
        quoteLineItem=[select CreatedDate,Quantity__c,UnitPrice__c,TotalPrice__c,ListPrice__c,Product__r.Name,QuoteId__c  from QuoteLineItem__c where QuoteId__c=:quoteId ];
       system.debug(quoteLineItem);
        
    }
    
    
    
}