force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/ContractId__c.field-meta.xml
<CustomField>
    <fullName>ContractId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Number</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveDate__c</fullName>
    <label>Order Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderSuccessMailHandlerTest.cls
@isTest
private class OrderSuccessMailHandlerTest {

    @isTest static void testHandleInsert() {
        Account testAccount = new Account(Name ='Test Account');
        insert testAccount;
        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            Email = 'abc@gmail.com'
        );
        /* Contect  testContect= new Contact(
         FirstName='Test',
         LastName='Contact',
         Email='abc@gmail.com                
         ) */
        insert testContact;
        Contract testContract = new Contract(
            AccountId = testAccount.Id,
            Status = 'Draft', 
            StartDate = Date.today(),
            ContractTerm=8,
            CustomerSignedId = testContact.Id
        );
        insert testContract;
        Order__c testOrder = new Order__c(
            Name = 'Test Order',
            ContractId__c = testContract.Id,
            AccountId__c = testAccount.Id,
            EffectiveDate__c = System.today(),
            Status__c = 'Draft'
            
        );
        insert testOrder;
        
        List<Order__c> orderList = new List<Order__c>{testOrder};
        Test.startTest();
        orderSucessMailHandler.handleInsert(orderList);
        Test.stopTest();

       
    }
}