force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <displayFormat>{00000000}</displayFormat>
    <label>Order Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>Order Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <label>Order Product</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Order Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/Product2Id__c.field-meta.xml
<CustomField>
    <fullName>Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InvoiceController.cls
public class InvoiceController {
    public Order__c ord{get;set;}
    public id orderId{get;set;}
    public list<OrderItem__c> orderitem{get;set;}
    public InvoiceController(){
        orderId = ApexPages.currentPage().getParameters().get('id');
        system.debug('order  id '+orderId);
        ord=[SELECT  AccountId__r.Name,CreatedDate,TotalAmount__c,OrderNumber__c,BillingAddress__PostalCode__s, BillingAddress__City__s, BillingAddress__CountryCode__s,BillingAddress__Street__s,BillingAddress__StateCode__s,ShippingAddress__City__s,ShippingAddress__CountryCode__s,ShippingAddress__Street__s,ShippingAddress__PostalCode__s, ShippingAddress__StateCode__s,Name FROM Order__c Where Id=:orderId];
        orderitem=[select TotalPrice__c,UnitPrice__c,Quantity__c,ListPrice__c,Product2Id__r.Name,CreatedDate from OrderItem__c  where OrderId__c=:orderId];
        system.debug('list of quote line item'+orderitem);
    }

}